export function mapBackendOrderAdmin(item) {
  return {
    id: item.id,
    orderCode: item.orderCode || `ORD-${item.id ?? '--'}`,
    sessionId: item.sessionId || '--',
    customerName: item.customerName ?? '',
    customerPhone: item.customerPhone ?? '',
    customerEmail: item.customerEmail ?? '',
    currencyCode: item.currencyCode || 'NRS',
    subtotalAmount: Number(item.subtotalAmount ?? 0),
    discountAmount: Number(item.discountAmount ?? 0),
    taxAmount: Number(item.taxAmount ?? 0),
    shippingAmount: Number(item.shippingAmount ?? 0),
    grandTotalAmount: Number(item.grandTotalAmount ?? 0),
    status: item.status || 'PENDING_PAYMENT',
    notes: item.notes || '',
    itemCount: Number(item.itemCount ?? 0),
    createdAt: item.createdAt || null,
    paymentSubmissionId: item.paymentSubmissionId ?? null,
    paymentProvider: item.paymentProvider || null,
    paymentVerificationStatus: item.paymentVerificationStatus || null,
    expectedAmount: item.expectedAmount != null ? Number(item.expectedAmount) : null,
    paidAmount: item.paidAmount != null ? Number(item.paidAmount) : null,
    payerMobile: item.payerMobile || '',
    transactionReference: item.transactionReference || '',
    receiptImageUrl: item.receiptImageUrl || '',
    paymentRemarks: item.paymentRemarks || '',
    submittedAt: item.submittedAt || null,
  };
}
